### ISSUE TITLE
metadata for experiments

### ISSUE THREAD

**Issue by christophlohrmann** [zincware/MDSuite#242]
**What feature would you like to see added?**
store metadata of any kind on experiments.
In the project, the values of the experiments should be accessible through the parameters of the experiments 

**Describe how this feature would improve the code**
Then I don't need to do that manually

**Describe how this feature would work/possible implementations**
no idea

**User story**
I run 100 simulations, varying 2 obscure parameters like packing fraction and flagellar unbundling rate.
I the want a plot of the Diffusion coefficient vs unbundling rate, with a different line color for each packing fraction.
To do that I would like tabulated data like

exp_id | pack_f | unbundle_rate | ... [all other metadata like time step, Temperature, vox volume etc] ... | msd
0        | 0.2    |   16.4  | [...] | 2e-8
1        | 0.2    |   16.8  | [...]  | 2.5e-8
2        | 0.1    |   16.4  | [...]  | 7e6
.
.
.

**Comment by SamTov** [comment]
We have two options with this implementation. One is of course to simply have attributes that can be arbitrarily added to the Experiment class as:

```python
exa = Experiment(...)
exa.volume_fraction = 0.1
```

Alternatively -- an in my opinion preferably -- we have a meta_data dictionary attribute in which we should also have the temperature and perhaps even the time_step as it is meta-data of the simulation. This could also be referred to as simulation_parameters in line with previous discussion about incorporating simulation data into the code. It could look something like:

```python
exa = Experiment(...)
exa.simulation_data = {'time_step': 0.002, 'temperature': 100.5, 'volume_fraction': 0.1}
```

In the latter case, we will need to update the calculators to handle such an approach.

As this is all simulation data we could also consider storing it in a yaml file rather than the SQL database as the structure would be simple. It would also allow the data to be trivially read in upon loading an experiment or reading from a Project class.

**Comment by SamTov** [comment]
I am thinking that this data should be stored in a table in the analysis database (perhaps renaming would be better). That way it is never stored in the class and we can almost do away with the saved class states and just have databases.

**Comment by PythonFZ** [comment]
#264 should also be ported to the database

**Comment by SamTov** [comment]
Perhaps, but I am not sure that it is quite the same level of importance.

**Comment by PythonFZ** [comment]
> Perhaps, but I am not sure that it is quite the same level of importance.

I added it here, so we can consider it when developing the new database. Otherwise we might forget about it.

**Comment by SamTov** [comment]
very true
