### ISSUE TITLE
mdsuite changes matplotlib style

### ISSUE THREAD

**Issue by christophlohrmann** [zincware/MDSuite#246]
**Describe the bug**
When importing mdsuite, the matplotlib style is set to 'classic'.

**To Reproduce**
plot anything with matplotlib after ``import mdsuite`` and you will get the 'classic' style.

**Expected behavior**
mdsuite not to change global states of other modules.
when plotting, ``mdsuite`` should either use the user settings or revert to them when it is done.

``matplotlib.style.use('default')`` after ``import mdsuite`` brings me back to what I want, but I'd rather not do that everytime

**Comment by SamTov** [comment]
Yes we have some custom setting as well in some of the calculators. I guess we should apply the style to our plots and then set the style back to default at the end of the computation. This should be simple in the `calculator.py` file after run computation. I will take a look.

**Comment by SamTov** [comment]
I have been thinking a lot about the plotting in MDSuite recently. I think that we should move away from trying to construct publication quality plots and move more towards making plots for the purpose of data exploration. Therefore, we should shift out attention to something like Plotly or pyqtgraph which have far better user interfacing options and are more powerful for complicated data.

**Comment by Fratorhe** [comment]
I think the plotting should be as simple and user friendly as possible. 
Normally, each user would like a different style (fonts, colors, etc), and I think this is easier to plot with a little script afterwards since all the data is always saved in the DBs. 
I would either keep the basic Matplotlib, or maybe plotly could be another option as it offers nicer interface.
