### ISSUE TITLE
Reduction of the calculator class.

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#287]
**Describe the bug**
The calculator class should probably be reduced in size. Many of the methods apply only to some of the calculators. I would suggest we discuss what kinds of parent classes we could use for some of the calculators as they do generally take on some common form. In this case, the calculator class would be quite minimal and act as a good template for custom calculators.

**Comment by PythonFZ** [comment]
The functions in question are probably the following:

https://github.com/zincware/MDSuite/blob/dd9f147316ad9eb118a71eca2c400b4821f27aec/mdsuite/calculators/calculator.py#L236-L370

https://github.com/zincware/MDSuite/blob/dd9f147316ad9eb118a71eca2c400b4821f27aec/mdsuite/calculators/calculator.py#L512-L568

Because they are used in mutiple calculators, we could consider having multiple parent classes.
`Calculator -> EinsteinCalculators -> EinsteinDiffusionCoefficient` for `_msd_operation`
The would make them easier to maintain and slim the base class a lot.

I would also argue that we should agree on one plotting method:
https://github.com/zincware/MDSuite/blob/dd9f147316ad9eb118a71eca2c400b4821f27aec/mdsuite/calculators/calculator.py#L455-L497

With the upcoming "active experiments" we might want to change the plotting all together, so that multiple experiments can be plotted over each other.

We might want to go through all the functions and see, if they are up to date and really need to be there.
E.g., 
https://github.com/zincware/MDSuite/blob/dd9f147316ad9eb118a71eca2c400b4821f27aec/mdsuite/calculators/calculator.py#L499-L510

Does not use logging, has a `sys.exit(1)` in it

https://github.com/zincware/MDSuite/blob/dd9f147316ad9eb118a71eca2c400b4821f27aec/mdsuite/calculators/calculator.py#L577-L578'

No docstrings, no functionality.

**Comment by SamTov** [comment]
Splitting into parent classes will be a good thing but also quite challenging here. We could go with dynamic vs static and just have GK and Einstein repeated. Or we can have an Einstein class and GK class and then maybe histogram class or something for the RDF/ADF/SDF. I think having a dynamic vs static would be nice as there would be one or two methods in each that are not called by all the child calculators but still it would be general and easy to use as a template.

Having then a grandparent class would be nice for custom experiments to understand exactly how they should be written as well as what methods are already available to them.

**Comment by SamTov** [comment]
closed with #325
