### ISSUE TITLE
Bokeh plots should be smaller.

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#375]
The plots are to large in JupyterLab

The following is taken from a 1920x1080 screen. They should be smaller.
![image](https://user-images.githubusercontent.com/46721498/140524325-e1f7bbac-a664-4020-9fd9-7f3b64d49815.png)

**Comment by Fratorhe** [comment]
In normal web visualization they are also too large in some cases. 
Should we consider some adaptive option? Or maybe start smaller in size to be on the safe side?

**Comment by SamTov** [comment]
The plots are already set to adaptive. Bokeh had some option to define a ration but they removed it. In the case of the web plots I would like to actually build them all into one html document with a nice css template. In this case sizing can be easily taken care of. In the Jupyter case, it is more what Jupyter finds okay. If there is a nice way to automatically re-scale the plots such that it works on all screens then I welcome the suggestion. 

I think that writing "They should be smaller" is a little challenging in terms of opening discussion. We should have some open conversation about how we can manage it, not necessarily demand that things change. We agree that we need some platform for exploratory data analysis which rules out MPL. We like Bokeh due to all of their plugins which make truly nice interactive plots and it has been nicely integrated. So let's work on how to get the scaling right.

**Comment by PythonFZ** [comment]
> I think that writing "They should be smaller" is a little challenging in terms of opening discussion

I agree that we should talk about scaling options for the plots. But in the current state they are to big in Jupyter Lab and that is something that should be changed to a reasonable size.

**Comment by SamTov** [comment]
```python
    def grid_show(self, figures: list):
        """
        Display a list of figures in a grid.

        Parameters
        ----------
        figures : list
                A list of figures to display.

        Returns
        -------

        """
        grid = gridplot(figures, ncols=3, sizing_mode="scale_both")
        show(grid)
```
Try changing the gridplot sizing mode argument to 'fixed'

**Comment by SamTov** [comment]
We can look at using the global Jupyter option to set the scale for these notebooks.

**Comment by SamTov** [comment]
So in the case of my Jupyter lab and notebooks the figures are fine for more than on plot.

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/47057691/144223541-68899808-9407-4c4b-bace-7e5cd676c69e.png">

For a single plot they are much too large.

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/47057691/144223662-ccf18d3b-8bcd-483f-8719-a14941e4ea1c.png">
