### ISSUE TITLE
Handle single snapshot trajectories

### ISSUE THREAD

**Issue by Fratorhe** [zincware/MDSuite#379]
**What feature would you like to see added?**
For some computations we may want only a single snapshot eg. RDF, rings statistics (when implemented). 
Current reader gets the two first configurations to compute the sampling rate. 
Therefore, in the case of a single snapshot the code crashes. 

**Describe how this feature would work/possible implementations**
I have implemented it locally with a simple try/except block. 
However, I'd link this to the PR for the new file readers #372 since it makes more sense to do it in the new ones already.

**Comment by SamTov** [comment]
We could have a `trajectory=True` argument in the file reader that tells the `get_system_properties` method whether or not it is looking at a dynamic trajectory or snapshots.

**Comment by Fratorhe** [comment]
I am not sure if it is needed to add this argument.
The code should be able to check if there is a single snapshot or more than one.
Unless we can point to a snapshot, which I am not sure if it is useful to have... (the user can export the snapshot somewhere else)

**Comment by SamTov** [comment]
I don't mind the idea of arguments because as @christophlohrmann and @PythonFZ and I have discussed locally, there may come a time, sort of like now, where people want to do non time related analysis. This would be common with things like monte-carlo or in your case just snapshots of simulations where the time between frames is actually meaningless.

**Comment by Fratorhe** [comment]
Yes, indeed. 
What I meant is that I do not know if it is necessary to create the distinction, or if the code should be "smart" enough to understand that there is only one snapshot. Maybe for the other applications you mention it is necessary. 

In that case, calculators that require time evolution should give an error if used in snapshots, while calculators for snapshots should perform the calculation for each snapshot.

**Comment by SamTov** [comment]
I think formulating a single snapshot as a minimal working example of un-ordered data makes sense to me. So have a keyword and for a single snapshot that is just automatically implied.

**Comment by christophlohrmann** [comment]
The whole metadata (timestep, sample step. temperature, pressure, box_size, ...) needs a thorough look at.
Some file formats provide the metadata, some don't. Some calculators need certain data, but for some input data values like time step do not even exist.
We need general methods to provide the metadata that is not in the file as well as a check for each calculator, which metadata it needs to perform the computation.
Then the user has time to add all the missing information before the first calculator call

**Comment by christophlohrmann** [comment]
as for the lammps one-snapshot example at hand, I would say if the user provides the timestep, we do not need to look for it.
e.g. rather than a ``trajectory=True`` kwarg I would more like a ``time_step=None`` keyword such that only if it is not None, we look for the time step in the file

**Comment by SamTov** [comment]
Well one thing is that when we refer to time step we talk about a piece of meta-data. What you get from the trajectory isa sample rate which is why it read in two configurations. 

We could start reading time stamps from the trajectory, I am in favour of this but it is a little bit specific to certain format. For binary files we will probably either need to read time steps or we will have to have the user pass a sample rate to the code anyway.

**Comment by christophlohrmann** [comment]
I think sample_rate and time_step should be combined to sample_step. It should be an optional metadata value that some calculators can access if needed and raise an error if it is not there. 
If the trajectory file gives the opportunity to infer the sample_step, it should be done. Otherwise the user has to provide the value somewhere else before calling time-dependent calculators

**Comment by SamTov** [comment]
That works for me. The only extension of generality here is what if they have say 100 time steps, then they ran another 500 and forgot to save it, then started dumping them again. Can you still get dynamics from this? Technically an Einstein computation would be fine but maybe questionable. Or should you just get your MSD from after a certain time and so we just need this offset to be implemented.

**Comment by christophlohrmann** [comment]
I do not think we should support data gaps in time-dependent calculators.

**Comment by SamTov** [comment]
If we have the time-step it is relatively trivial to do so. But for now we can ignore it.

**Comment by christophlohrmann** [comment]
I agree it can be done. I do not agree on the trivial part :)

**Comment by SamTov** [comment]
@christophlohrmann is this resolved?
