### ISSUE TITLE
tests fail on main

### ISSUE THREAD

**Issue by christophlohrmann** [zincware/MDSuite#510]
Tests fail because DataHub has changed.

Possible solution: Make it such that you can use specific versions of DataHub and MDSuite says which version it needs.
With that you can change Datahub (and reflect the update with a version change in a PR on mdsuite) without affecting any other branch of mdsuite.

**Comment by PythonFZ** [comment]
Will be fixed by introducing `tag` in https://github.com/zincware/ZincHub/pull/3

This will require the keyword `tag` on all occurrences of `zinchub`. It will also prohibit using data straight from main and instead require a new tag for all changes, ideally providing a description on why the data was updated.
