### ISSUE TITLE
Remove Experiments not easily possible

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#540]
**Describe the bug**
Running a calculator should not create an experiment

**To Reproduce**
1. Add multiple experiments
2. Remove the directory in `Project/<exp>`
3. Restart Kernel
4. Run calculator
5. Error: a new experiment will be create for you

**Comment by SamTov** [comment]
I think the problem here or, bug, is two things. One we need a way to delete experiments but we also need to protect the creation of new experiments. When a project is loaded, the pipeline could load all experiments such that it is never called again, this would avoid the bug being alluded to here.

Ideally, we add a project method that deletes experiments.

**Comment by SamTov** [comment]
Duplicate of #343
